name: Ejecutar pruebas con Testcontainers

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Ejecutar mvn test
        run: mvn test
